# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_axi_gpio_0_0/micro_blaze_button_axi_gpio_0_0.xci
# IP: The module: 'micro_blaze_button_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_axi_gpio_0_0/micro_blaze_button_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_blaze_button_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_axi_gpio_0_0/micro_blaze_button_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_blaze_button_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_axi_gpio_0_0/micro_blaze_button_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_blaze_button_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_axi_gpio_0_0/micro_blaze_button_axi_gpio_0_0.xci
# IP: The module: 'micro_blaze_button_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_axi_gpio_0_0/micro_blaze_button_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_blaze_button_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_axi_gpio_0_0/micro_blaze_button_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_blaze_button_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_axi_gpio_0_0/micro_blaze_button_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_blaze_button_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
