# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/micro_blaze_FND/micro_blaze_FND.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND || ORIG_REF_NAME==micro_blaze_FND} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_clk_wiz_0_0/micro_blaze_FND_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_clk_wiz_0_0 || ORIG_REF_NAME==micro_blaze_FND_clk_wiz_0_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_microblaze_0_0/micro_blaze_FND_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_microblaze_0_0 || ORIG_REF_NAME==micro_blaze_FND_microblaze_0_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_dlmb_v10_0/micro_blaze_FND_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_dlmb_v10_0 || ORIG_REF_NAME==micro_blaze_FND_dlmb_v10_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_ilmb_v10_0/micro_blaze_FND_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_ilmb_v10_0 || ORIG_REF_NAME==micro_blaze_FND_ilmb_v10_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_dlmb_bram_if_cntlr_0/micro_blaze_FND_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==micro_blaze_FND_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_ilmb_bram_if_cntlr_0/micro_blaze_FND_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==micro_blaze_FND_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_lmb_bram_0/micro_blaze_FND_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_lmb_bram_0 || ORIG_REF_NAME==micro_blaze_FND_lmb_bram_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_mdm_1_0/micro_blaze_FND_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_mdm_1_0 || ORIG_REF_NAME==micro_blaze_FND_mdm_1_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_rst_clk_wiz_0_100M_0/micro_blaze_FND_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==micro_blaze_FND_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_axi_uartlite_0_0/micro_blaze_FND_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_axi_uartlite_0_0 || ORIG_REF_NAME==micro_blaze_FND_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_xbar_0/micro_blaze_FND_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_xbar_0 || ORIG_REF_NAME==micro_blaze_FND_xbar_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_microblaze_0_axi_periph_0/micro_blaze_FND_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_microblaze_0_axi_periph_0 || ORIG_REF_NAME==micro_blaze_FND_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_axi_gpio_0_0/micro_blaze_FND_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_axi_gpio_0_0 || ORIG_REF_NAME==micro_blaze_FND_axi_gpio_0_0} -quiet] -quiet

# IP: bd/micro_blaze_FND/ip/micro_blaze_FND_axi_gpio_1_0/micro_blaze_FND_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_blaze_FND_axi_gpio_1_0 || ORIG_REF_NAME==micro_blaze_FND_axi_gpio_1_0} -quiet] -quiet

# XDC: bd/micro_blaze_FND/micro_blaze_FND_ooc.xdc
