# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.cache/wt [current_project]
set_property parent.project_path C:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/minkyu/AppData/Roaming/Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/hdl/micro_blaze_FND_wrapper.v
add_files C:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/micro_blaze_FND.bd
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_clk_wiz_0_0/micro_blaze_FND_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_clk_wiz_0_0/micro_blaze_FND_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_clk_wiz_0_0/micro_blaze_FND_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_microblaze_0_0/micro_blaze_FND_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_microblaze_0_0/micro_blaze_FND_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_microblaze_0_0/micro_blaze_FND_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_dlmb_v10_0/micro_blaze_FND_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_dlmb_v10_0/micro_blaze_FND_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_ilmb_v10_0/micro_blaze_FND_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_ilmb_v10_0/micro_blaze_FND_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_dlmb_bram_if_cntlr_0/micro_blaze_FND_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_ilmb_bram_if_cntlr_0/micro_blaze_FND_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_lmb_bram_0/micro_blaze_FND_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_mdm_1_0/micro_blaze_FND_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_mdm_1_0/micro_blaze_FND_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_rst_clk_wiz_0_100M_0/micro_blaze_FND_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_rst_clk_wiz_0_100M_0/micro_blaze_FND_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_rst_clk_wiz_0_100M_0/micro_blaze_FND_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_uartlite_0_0/micro_blaze_FND_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_uartlite_0_0/micro_blaze_FND_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_uartlite_0_0/micro_blaze_FND_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_xbar_0/micro_blaze_FND_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_gpio_0_0/micro_blaze_FND_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_gpio_0_0/micro_blaze_FND_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_gpio_0_0/micro_blaze_FND_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_gpio_1_0/micro_blaze_FND_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_gpio_1_0/micro_blaze_FND_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_axi_gpio_1_0/micro_blaze_FND_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/micro_blaze_FND_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/minkyu/Documents/GitHub/SOC_Design_VerilogPractice/SOC_Practice_soc/SOC_Practice_soc.srcs/sources_1/bd/micro_blaze_FND/ip/micro_blaze_FND_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top micro_blaze_FND_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef micro_blaze_FND_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file micro_blaze_FND_wrapper_utilization_synth.rpt -pb micro_blaze_FND_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
